inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'archive/**/*'
    - 'vendor/**/*'
    - 'design/**/*'
    - 'tools/**/*'
    - 'db/schema.rb'

Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/deploy.rb'

Style/HashSyntax:
  EnforcedShorthandSyntax: either

