inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'archive/**/*'
    - 'vendor/**/*'
    - 'design/**/*'
    - 'tools/**/*'
    - 'db/schema.rb'

Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/deploy.rb'

