language: ruby
rvm:
  - 2.0.0
branches:
  only:
    - master
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
  - "cp config/database.yml.example config/database.yml"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script: RAILS_ENV=test rake sunspot:solr:start
after_script: RAILS_ENV=test rake sunspot:solr:stop

