language: ruby
services:
  - docker
notifications:
  email:
    on_success: change
    on_failure: change
branches:
  except:
    # starting with depfu/
    - /^depfu\/.*/
install:
  - true
before_script:
  - 'cat docker-compose.override.yml.example |sed "s/CONTAINER_USERID: 13042/CONTAINER_USERID: $(id -u)/" > docker-compose.override.yml'
  - 'docker-compose run --rm hackweek bundle exec rake dev:bootstrap'
script:
  - 'docker-compose run --rm hackweek bundle exec rspec'
