#!/usr/bin/ruby

require "rubygems"
require "nokogiri"

def squash_whitespace text
  text.gsub! /^\ */, ""
  text.gsub! /\ *$/, ""
  text.gsub! /\ \ +/, " "
  text
end

def format_list list
  if list.size == 0
    return ""
  end
  
  out = "\n"
  list.each do |li|
    out += "* " + li.text + "\n"
  end
  out += "\n"

  out
end

def format_richtext richtext
  out = ""
  richtext.xpath( "p" ).each do |p|
    out += p.text + "\n\n"
  end
  
  out += format_list richtext.xpath( "ul/li" )
  out += format_list richtext.xpath( "ol/li" )

  out
end

output = ARGV[0]

if !output
  STDERR.puts "Usage: features2markdown <output-directory>"
  exit 1
end

if !File.exists? output
  STDERR.puts "Error: output directory '#{output}' doesn't exist."
  exit 1
end

features_file = File.expand_path('../../archive/fate.xml',__FILE__)

doc = Nokogiri::XML(File.read(features_file))

doc.xpath( "//feature" ).each do |feature|
  title = feature.xpath("title").text
  
  next if title =~ /\//

  filename = title.gsub( / /, "-" ) + ".md"
  
  puts "Creating #{filename}"
  
  File.open( output + "/" + filename, "w" ) do |f|
    f.puts "## Description"
    f.puts ""
    description = feature.xpath("description/richtext")
    f.puts squash_whitespace( format_richtext( description ) )
    f.puts ""
    
    f.puts "## People"
    f.puts ""
    f.puts "Clark Kent originated this idea."
    f.puts ""
    f.puts "Bruce Wayne and Peter Parker plan to work on it."
    f.puts ""

    f.puts "## Status"
    f.puts ""
    f.puts "Project in progress"
    f.puts ""
    
    f.puts "## Related material"
    f.puts ""
    f.puts "*Put references to additional material here.*"
    f.puts ""
    
    f.puts "## Comments"
    f.puts ""
    
    feature.xpath("discussion/comment").each do |c|
      name = c.xpath('author/person/fullname').text
      name.gsub! /\n*/, ""
      f.puts "*by #{squash_whitespace( name )}*"
      f.puts ""
      f.puts squash_whitespace( format_richtext( c.xpath("richtext") ) )
      f.puts ""
    end
  end
end
