#!/usr/bin/ruby

require "rubygems"
require "haml"

def render_title
  @title
end

def render_content
  @content
end

output = ARGV[0]

if !output
  STDERR.puts "Usage: generate_project_index <output-directory>"
  exit 1
end

if !File.exists? output
  STDERR.puts "Error: output directory '#{output}' doesn't exist."
  exit 1
end

projects = Hash.new

Dir.entries( output ).each do |entry|
  next if entry !~ /\.html$/
  
  File.open( output + "/" + entry ).each_line do |line|
    if line =~ /<h1>(.*)<\/h1>/
      title = $1
      projects[title] = entry
      break
    end
  end
end
  
puts "Creating index.html"

@title = "Past Projects"

@content = "<p>Here is a list of projects and ideas from previous hack weeks. "
@content += "Use it as inspiration for your own ideas, or join and continue a "
@content += "project which interests you.</p>\n"

@content += "<ul>\n"

projects.keys.sort.each do |title|
  filename = projects[title]
  @content += "  <li><a href='#{filename}'>#{title}</a></li>\n"
end

@content += "</ul>\n"

template = File.read File.expand_path('../templates/page.haml', __FILE__ )
engine = Haml::Engine.new template

File.open output + "/index.html", "w" do |file|
  file.puts engine.render( binding )
end
