#!/usr/bin/ruby

require "json"

def extract_tags string
  tags = string.split(/[, ]/).reject { |t| t.empty? }
  tags.map { |t| t.strip }
end

wiki_dir = ARGV[0]

if !wiki_dir
  STDERR.puts "Usage: projects2json <wiki-directory>"
  exit 1
end

if !File.exists? wiki_dir
  STDERR.puts "Error: wiki directory '#{wiki_dir}' doesn't exist."
  exit 1
end

category_list = Hash.new
tag_list = Hash.new

projects = Array.new

Dir.entries( wiki_dir ).each do |entry|
  entry =~ /(.*)\.md$/
  page = $1
  next unless page
  next if ["Home","'Categories'","'Tags'","'Template'"].include? page
  
  project = Hash.new

  project[:title] = page

  description = ""
  File.open( wiki_dir + "/" + entry ).each_line do |line|
    if line =~ /\*\*Categories.?\*\*(.*)/
      project[:categories] = extract_tags $1
    elsif line =~ /\*\*Tags.?\*\*(.*)/
      project[:tags] = extract_tags $1
    else
      description += line
    end
  end
  
  project[:description] = description
    
  projects.push project
end

output = Hash.new
output[ :projects ] = projects

puts JSON.pretty_generate output
